'use client';
import { useEffect, useState } from 'react';
import { toast } from 'sonner';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Textarea } from '@/components/ui/textarea';
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table';
const methods = [['cash','Cash'],['bank_transfer','Bank transfer'],['upi','UPI'],['card','Card'],['online','Online'],['other','Other']];
async function request(path, options = {}) { const token = typeof window !== 'undefined' ? localStorage.getItem('g360_token') : null; const response = await fetch('/api' + path, { ...options, headers: { 'Content-Type':'application/json', ...(token ? { Authorization:'Bearer ' + token } : {}), ...(options.headers || {}) } }); const data = await response.json().catch(() => ({})); if (!response.ok) throw new Error(data.error || 'Request failed'); return data; }
const money = (minor, currency = 'INR') => new Intl.NumberFormat('en-IN', { style:'currency', currency, maximumFractionDigits:2 }).format((minor || 0) / 100);
export default function Payments({ organizationId }) {
 const [items,setItems] = useState([]); const [memberships,setMemberships] = useState([]); const [students,setStudents] = useState([]); const [createOpen,setCreateOpen] = useState(false); const [selected,setSelected] = useState(null); const [saving,setSaving] = useState(false);
 const [form,setForm] = useState({ amount_minor:'', currency:'INR', payment_method:'cash', membership_id:'', credit_quantity:'', description:'' });
 const load=async()=>{ try { const [payments,ms,ss]=await Promise.all([request('/payments'),request('/memberships'),request('/students')]); setItems(payments.items||[]); setMemberships(ms.items||[]); setStudents(ss.items||[]); } catch(e){ toast.error(e.message); } };
 useEffect(()=>{load();},[]);
 const studentName=(id)=>{const s=students.find(x=>x.id===id); return s ? [s.first_name,s.last_name].filter(Boolean).join(' ') : id;};
 const create=async()=>{setSaving(true); try { const p=await request('/payments',{method:'POST',headers:{'Idempotency-Key':crypto.randomUUID()},body:JSON.stringify({amount_minor:Math.round(Number(form.amount_minor)*100),currency:form.currency,payment_method:form.payment_method,description:form.description, organization_id: organizationId})}); setCreateOpen(false); setForm({...form,amount_minor:'',membership_id:'',credit_quantity:'',description:''}); setSelected(p); await load(); toast.success('Payment Transaction created as draft'); } catch(e){toast.error(e.message);} finally{setSaving(false);}};
 const post=async()=>{ if(!selected)return; setSaving(true); try { const body={organization_id: organizationId, allocations:[{membership_id:form.membership_id,amount_minor:Math.round(Number(form.amount_minor)*100),credit_quantity:Number(form.credit_quantity),description:form.description}]}; const p=await request('/payments/'+selected.id,{method:'POST',headers:{'Idempotency-Key':crypto.randomUUID()},body:JSON.stringify(body)}); setSelected(p.payment); setForm({...form,amount_minor:'',membership_id:'',credit_quantity:'',description:''}); await load(); toast.success('Payment posted and credits granted'); } catch(e){toast.error(e.message);} finally{setSaving(false);}};
 const refund=async()=>{if(!selected)return; const amount=window.prompt('Refund amount'); if(!amount)return; try { const p=await request('/payments/'+selected.id,{method:'POST',headers:{'Idempotency-Key':crypto.randomUUID()},body:JSON.stringify({command:'refund',organization_id: organizationId,amount_minor:Math.round(Number(amount)*100),description:'Administrator refund'})}); setSelected(p.payment); await load(); toast.success('Refund posted as compensating allocation'); } catch(e){toast.error(e.message);}};
 return <div className="space-y-5"><div className="flex items-center justify-between"><div><h1 className="text-2xl font-bold">Payments</h1><p className="text-sm text-muted-foreground">Create, post, and refund Payment Transactions.</p></div><Button onClick={()=>setCreateOpen(true)}>Create Payment</Button></div>
 <div className="rounded-2xl glass overflow-hidden"><Table><TableHeader><TableRow><TableHead>Receipt</TableHead><TableHead>Status</TableHead><TableHead>Amount</TableHead><TableHead>Created</TableHead><TableHead>Actions</TableHead></TableRow></TableHeader><TableBody>{items.map(p=><TableRow key={p.id} onClick={async()=>{setSelected((await request('/payments/'+p.id)).payment);}}><TableCell className="font-mono">{p.receipt_number}</TableCell><TableCell>{p.status}</TableCell><TableCell>{money(p.amount_minor,p.currency)}</TableCell><TableCell>{new Date(p.created_at).toLocaleString()}</TableCell><TableCell>{p.status==='posted'||p.status==='partially_refunded'?<Button size="sm" variant="outline" onClick={(e)=>{e.stopPropagation();setSelected(p);}}>Refund</Button>:null}</TableCell></TableRow>)}</TableBody></Table></div>
 <Dialog open={createOpen} onOpenChange={setCreateOpen}><DialogContent><DialogHeader><DialogTitle>Create Payment Transaction</DialogTitle><DialogDescription>Creation records money received as a draft. Credits are granted only when you post it.</DialogDescription></DialogHeader><div className="grid gap-3"><div><Label>Amount</Label><Input type="number" step="0.01" value={form.amount_minor} onChange={e=>setForm({...form,amount_minor:e.target.value})}/></div><div><Label>Currency</Label><Input value={form.currency} onChange={e=>setForm({...form,currency:e.target.value})}/></div><div><Label>Payment method</Label><Select value={form.payment_method} onValueChange={v=>setForm({...form,payment_method:v})}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{methods.map(([v,l])=><SelectItem key={v} value={v}>{l}</SelectItem>)}</SelectContent></Select></div><Textarea placeholder="Administrator description" value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></div><DialogFooter><Button onClick={create} disabled={saving||!Number(form.amount_minor)}>Create draft</Button></DialogFooter></DialogContent></Dialog>
 {selected&&<Dialog open={!!selected} onOpenChange={v=>!v&&setSelected(null)}><DialogContent><DialogHeader><DialogTitle>{selected.receipt_number}</DialogTitle><DialogDescription>{selected.status} · {money(selected.amount_minor,selected.currency)}</DialogDescription></DialogHeader>{selected.status==='draft'&&<div className="grid gap-3"><div><Label>Membership</Label><Select value={form.membership_id} onValueChange={v=>setForm({...form,membership_id:v})}><SelectTrigger><SelectValue placeholder="Choose Membership"/></SelectTrigger><SelectContent>{memberships.map(m=><SelectItem key={m.id} value={m.id}>{studentName(m.student_id)} · {m.id.slice(0,8)}</SelectItem>)}</SelectContent></Select><Input className="mt-2" type="number" step="0.01" placeholder="Amount allocated" value={form.amount_minor} onChange={e=>setForm({...form,amount_minor:e.target.value})}/><Input className="mt-2" type="number" placeholder="Credits granted" value={form.credit_quantity} onChange={e=>setForm({...form,credit_quantity:e.target.value})}/><Textarea className="mt-2" placeholder="Allocation description" value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/><Button className="mt-3" onClick={post} disabled={saving||!form.membership_id||!Number(form.amount_minor)}>Post Payment and Grant Credits</Button></div></div>}{selected.status==='posted'||selected.status==='partially_refunded'?<Button onClick={refund}>Refund</Button>:null}</DialogContent></Dialog>}</div>;
}
